# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
is_ascending.numeric <- function(x) {
    .Call('_isit_is_ascending_numeric', PACKAGE = 'isit', x)
}

#' @export
is_strictly_ascending.numeric <- function(x) {
    .Call('_isit_is_strictly_ascending_numeric', PACKAGE = 'isit', x)
}

#' @export
is_descending.numeric <- function(x) {
    .Call('_isit_is_descending_numeric', PACKAGE = 'isit', x)
}

#' @export
is_strictly_descending.numeric <- function(x) {
    .Call('_isit_is_strictly_descending_numeric', PACKAGE = 'isit', x)
}

#' @export
is_ascending.integer <- function(x) {
    .Call('_isit_is_ascending_integer', PACKAGE = 'isit', x)
}

#' @export
is_strictly_ascending.integer <- function(x) {
    .Call('_isit_is_strictly_ascending_integer', PACKAGE = 'isit', x)
}

#' @export
is_descending.integer <- function(x) {
    .Call('_isit_is_descending_integer', PACKAGE = 'isit', x)
}

#' @export
is_strictly_descending.integer <- function(x) {
    .Call('_isit_is_strictly_descending_integer', PACKAGE = 'isit', x)
}

